'use client';
import { useState } from 'react';

type Tool = 'home' | 'profile' | 'posts';
type ProfileResult = {
  overallScore: number;
  headlineScore: number;
  aboutScore: number;
  experienceScore: number;
  skillsScore: number;
  summary: string;
  optimizedHeadline: string;
  optimizedAbout: string;
  optimizedExperience: string[];
  optimizedSkills: string[];
  keywordsToAdd: string[];
  keywordsToRemove: string[];
  profileChecks: { section: string; status: 'pass'|'fail'|'warn'; issue: string; fix: string }[];
  connectionTips: string[];
  visibilityTips: string[];
  nextActions: { today: string[]; thisWeek: string[]; thisMonth: string[] };
};
type PostResult = {
  posts: {
    format: string;
    hook: string;
    body: string;
    cta: string;
    fullPost: string;
    whyItWorks: string;
    bestTime: string;
    hashtags: string[];
  }[];
  contentStrategy: string;
  profileNotes: string;
};

export default function Home() {
  const [tool, setTool] = useState<Tool>('home');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [profileResult, setProfileResult] = useState<ProfileResult | null>(null);
  const [postResult, setPostResult] = useState<PostResult | null>(null);

  // Profile form
  const [headline, setHeadline] = useState('');
  const [about, setAbout] = useState('');
  const [experience, setExperience] = useState('');
  const [skills, setSkills] = useState('');
  const [education, setEducation] = useState('');
  const [goal, setGoal] = useState('get clients');

  // Post form
  const [postTopic, setPostTopic] = useState('');
  const [postBackground, setPostBackground] = useState('');
  const [postGoal, setPostGoal] = useState('get clients');
  const [industry, setIndustry] = useState('');

  async function runProfileOptimizer() {
    if (!headline && !about) { setError('Please fill in at least your headline and about section.'); return; }
    setLoading(true); setError(''); setProfileResult(null);
    try {
      const res = await fetch('/api/linkedin', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ tool: 'profile', headline, about, experience, skills, education, goal }),
      });
      const data = await res.json();
      if (!data.ok) throw new Error(data.error);
      setProfileResult(data.data);
    } catch(e: unknown) {
      setError(e instanceof Error ? e.message : 'Something went wrong');
    }
    setLoading(false);
  }

  async function runPostGenerator() {
    if (!postTopic) { setError('Please enter a topic.'); return; }
    setLoading(true); setError(''); setPostResult(null);
    try {
      const res = await fetch('/api/linkedin', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ tool: 'posts', topic: postTopic, background: postBackground, goal: postGoal, industry }),
      });
      const data = await res.json();
      if (!data.ok) throw new Error(data.error);
      setPostResult(data.data);
    } catch(e: unknown) {
      setError(e instanceof Error ? e.message : 'Something went wrong');
    }
    setLoading(false);
  }

  function copy(text: string) {
    navigator.clipboard.writeText(text);
  }

  function downloadPDF() {
    if (!profileResult) return;
    const content = `
LINKEDIN PROFILE OPTIMIZATION REPORT
Generated by LinkedPro AI
=====================================

OVERALL SCORE: ${profileResult.overallScore}/100
Headline Score: ${profileResult.headlineScore}/100
About Score: ${profileResult.aboutScore}/100
Experience Score: ${profileResult.experienceScore}/100
Skills Score: ${profileResult.skillsScore}/100

SUMMARY
-------
${profileResult.summary}

OPTIMIZED HEADLINE
------------------
${profileResult.optimizedHeadline}

OPTIMIZED ABOUT SECTION
-----------------------
${profileResult.optimizedAbout}

OPTIMIZED EXPERIENCE DESCRIPTIONS
-----------------------------------
${profileResult.optimizedExperience?.map((e,i) => `${i+1}. ${e}`).join('\n')}

RECOMMENDED SKILLS
------------------
${profileResult.optimizedSkills?.join(', ')}

KEYWORDS TO ADD
---------------
${profileResult.keywordsToAdd?.join(', ')}

PROFILE CHECKS
--------------
${profileResult.profileChecks?.map(c => `[${c.status.toUpperCase()}] ${c.section}: ${c.issue}\nFix: ${c.fix}`).join('\n\n')}

CONNECTION & VISIBILITY TIPS
-----------------------------
${profileResult.connectionTips?.map((t,i) => `${i+1}. ${t}`).join('\n')}

NEXT ACTIONS
------------
TODAY:
${profileResult.nextActions?.today?.map(a => `• ${a}`).join('\n')}

THIS WEEK:
${profileResult.nextActions?.thisWeek?.map(a => `• ${a}`).join('\n')}

THIS MONTH:
${profileResult.nextActions?.thisMonth?.map(a => `• ${a}`).join('\n')}

=====================================
LinkedPro AI — linkedin-optimizer.vercel.app
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'linkedin-optimization-report.txt';
    a.click();
  }

  const scoreColor = (s: number) => s >= 80 ? '#00e5a0' : s >= 60 ? '#f59e0b' : '#ef4444';
  const statusColor = (s: string) => s === 'pass' ? '#00e5a0' : s === 'warn' ? '#f59e0b' : '#ef4444';

  return (
      <div style={{ minHeight: '100vh', background: '#080c14', color: '#e8edf5', fontFamily: "'DM Sans', 'Segoe UI', sans-serif" }}>

        {/* BG effects */}
        <div style={{ position: 'fixed', inset: 0, overflow: 'hidden', pointerEvents: 'none', zIndex: 0 }}>
          <div style={{ position: 'absolute', top: '-20%', left: '-10%', width: 600, height: 600, background: 'radial-gradient(circle, rgba(0,100,255,0.08) 0%, transparent 70%)', borderRadius: '50%' }} />
          <div style={{ position: 'absolute', bottom: '-10%', right: '-5%', width: 500, height: 500, background: 'radial-gradient(circle, rgba(0,229,160,0.06) 0%, transparent 70%)', borderRadius: '50%' }} />
          <div style={{ position: 'absolute', top: '40%', left: '50%', width: 800, height: 2, background: 'linear-gradient(90deg, transparent, rgba(0,100,255,0.1), transparent)', transform: 'translateX(-50%)' }} />
        </div>

        <div style={{ position: 'relative', zIndex: 1 }}>

          {/* NAV */}
          <nav style={{ borderBottom: '1px solid rgba(255,255,255,0.06)', padding: '0 40px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', height: 64 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              <div style={{ width: 32, height: 32, background: 'linear-gradient(135deg, #0064ff, #00e5a0)', borderRadius: 8, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 16, fontWeight: 900 }}>L</div>
              <span style={{ fontWeight: 700, fontSize: 18, letterSpacing: -0.5 }}>Linked<span style={{ color: '#0064ff' }}>Pro</span></span>
            </div>
            <div style={{ display: 'flex', gap: 8 }}>
              <button onClick={() => { setTool('home'); setProfileResult(null); setPostResult(null); setError(''); }} style={{ padding: '8px 16px', borderRadius: 8, border: 'none', background: 'transparent', color: '#64748b', fontSize: 13, cursor: 'pointer', fontWeight: 600 }}>← Home</button>
              {[{id:'profile',label:'Profile Optimizer'},{id:'posts',label:'Post Generator'}].map(t => (
                  <button key={t.id} onClick={() => { setTool(t.id as Tool); setError(''); }} style={{ padding: '8px 16px', borderRadius: 8, border: tool === t.id ? '1px solid #0064ff' : '1px solid rgba(255,255,255,0.1)', background: tool === t.id ? 'rgba(0,100,255,0.15)' : 'transparent', color: tool === t.id ? '#60a5fa' : '#94a3b8', cursor: 'pointer', fontSize: 13, fontWeight: 600 }}>
                    {t.label}
                  </button>
              ))}
            </div>
          </nav>

          {/* HOME */}
          {tool === 'home' && (
              <div style={{ maxWidth: 900, margin: '0 auto', padding: '100px 40px', textAlign: 'center' }}>
                <div style={{ display: 'inline-block', padding: '6px 16px', borderRadius: 100, border: '1px solid rgba(0,100,255,0.3)', background: 'rgba(0,100,255,0.08)', color: '#60a5fa', fontSize: 12, fontWeight: 600, letterSpacing: 1, marginBottom: 32 }}>
                  AI-POWERED LINKEDIN GROWTH
                </div>
                <h1 style={{ fontSize: 'clamp(42px, 7vw, 80px)', fontWeight: 900, lineHeight: 1.05, letterSpacing: -2, margin: '0 0 24px' }}>
                  Your LinkedIn.<br />
                  <span style={{ background: 'linear-gradient(135deg, #0064ff, #00e5a0)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>Completely Optimized.</span>
                </h1>
                <p style={{ fontSize: 18, color: '#64748b', maxWidth: 520, margin: '0 auto 48px', lineHeight: 1.7 }}>
                  Optimize your profile for maximum visibility. Generate viral posts that attract clients and opportunities.
                </p>
                <div style={{ display: 'flex', gap: 16, justifyContent: 'center', flexWrap: 'wrap' }}>
                  <button onClick={() => setTool('profile')} style={{ padding: '16px 32px', borderRadius: 12, background: 'linear-gradient(135deg, #0064ff, #0040cc)', border: 'none', color: 'white', fontSize: 16, fontWeight: 700, cursor: 'pointer', letterSpacing: -0.3 }}>
                    Optimize My Profile →
                  </button>
                  <button onClick={() => setTool('posts')} style={{ padding: '16px 32px', borderRadius: 12, background: 'transparent', border: '1px solid rgba(255,255,255,0.15)', color: '#e8edf5', fontSize: 16, fontWeight: 600, cursor: 'pointer' }}>
                    Generate Posts →
                  </button>
                </div>
                <div style={{ display: 'flex', gap: 24, justifyContent: 'center', marginTop: 64, flexWrap: 'wrap' }}>
                  {['Profile Score /100','Exact Rewrites','5 Viral Posts','PDF Report','100% Free'].map(f => (
                      <div key={f} style={{ display: 'flex', alignItems: 'center', gap: 8, color: '#64748b', fontSize: 13 }}>
                        <span style={{ color: '#00e5a0' }}>✓</span> {f}
                      </div>
                  ))}
                </div>
              </div>
          )}

          {/* PROFILE OPTIMIZER */}
          {tool === 'profile' && (
              <div style={{ maxWidth: 800, margin: '0 auto', padding: '48px 24px' }}>
                <div style={{ marginBottom: 40 }}>
                  <h2 style={{ fontSize: 32, fontWeight: 800, letterSpacing: -1, margin: '0 0 8px' }}>Profile Optimizer</h2>
                  <p style={{ color: '#64748b', fontSize: 15 }}>Paste your current profile content. AI will score, rewrite and optimize everything for maximum LinkedIn visibility.</p>
                </div>

                {!profileResult ? (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>

                      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
                        <div>
                          <label style={{ display: 'block', fontSize: 11, fontWeight: 700, color: '#64748b', letterSpacing: 1, marginBottom: 8 }}>YOUR GOAL</label>
                          <select value={goal} onChange={e => setGoal(e.target.value)} style={{ width: '100%', padding: '12px 16px', borderRadius: 10, background: '#0f1623', border: '1px solid rgba(255,255,255,0.08)', color: '#e8edf5', fontSize: 14 }}>
                            <option value="get clients">Get freelance clients</option>
                            <option value="get job">Get hired for a job</option>
                            <option value="build brand">Build personal brand</option>
                            <option value="network">Grow network & connections</option>
                          </select>
                        </div>
                      </div>

                      {[
                        { label: 'CURRENT HEADLINE', val: headline, set: setHeadline, placeholder: 'e.g. Full Stack Developer | React & Next.js | Building web apps', hint: 'Max 220 chars on LinkedIn', multi: false },
                        { label: 'ABOUT / SUMMARY SECTION', val: about, set: setAbout, placeholder: 'Paste your full About section here...', hint: 'This is the most important section for SEO', multi: true },
                        { label: 'EXPERIENCE DESCRIPTIONS', val: experience, set: setExperience, placeholder: 'Paste your job titles, companies and descriptions...', hint: 'Include all roles you want optimized', multi: true },
                        { label: 'SKILLS (current list)', val: skills, set: setSkills, placeholder: 'e.g. React, JavaScript, Node.js, UI/UX Design...', hint: 'List all your current skills', multi: false },
                        { label: 'EDUCATION (optional)', val: education, set: setEducation, placeholder: 'e.g. BSc Computer Science, University of...', hint: 'Optional but helps with completeness score', multi: false },
                      ].map(f => (
                          <div key={f.label}>
                            <label style={{ display: 'block', fontSize: 11, fontWeight: 700, color: '#64748b', letterSpacing: 1, marginBottom: 8 }}>{f.label}</label>
                            {f.multi ? (
                                <textarea value={f.val} onChange={e => f.set(e.target.value)} placeholder={f.placeholder} rows={4} style={{ width: '100%', padding: '14px 16px', borderRadius: 10, background: '#0f1623', border: '1px solid rgba(255,255,255,0.08)', color: '#e8edf5', fontSize: 14, resize: 'vertical', boxSizing: 'border-box', lineHeight: 1.6 }} />
                            ) : (
                                <input value={f.val} onChange={e => f.set(e.target.value)} placeholder={f.placeholder} style={{ width: '100%', padding: '14px 16px', borderRadius: 10, background: '#0f1623', border: '1px solid rgba(255,255,255,0.08)', color: '#e8edf5', fontSize: 14, boxSizing: 'border-box' }} />
                            )}
                            <div style={{ fontSize: 11, color: '#475569', marginTop: 4 }}>{f.hint}</div>
                          </div>
                      ))}

                      {error && <div style={{ padding: '12px 16px', borderRadius: 10, background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.3)', color: '#ef4444', fontSize: 14 }}>{error}</div>}

                      <button onClick={runProfileOptimizer} disabled={loading} style={{ padding: '16px 32px', borderRadius: 12, background: loading ? '#1e293b' : 'linear-gradient(135deg, #0064ff, #0040cc)', border: 'none', color: 'white', fontSize: 16, fontWeight: 700, cursor: loading ? 'not-allowed' : 'pointer', marginTop: 8 }}>
                        {loading ? '⟳ Analyzing & Optimizing...' : 'Optimize My LinkedIn Profile →'}
                      </button>
                    </div>
                ) : (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>

                      <button onClick={() => setProfileResult(null)} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 18px', borderRadius: 10, background: 'transparent', border: '1px solid rgba(255,255,255,0.1)', color: '#94a3b8', fontSize: 13, fontWeight: 600, cursor: 'pointer', width: 'fit-content' }}>← Back</button>

                      {/* SCORES */}
                      <div style={{ background: '#0f1623', borderRadius: 16, padding: 28, border: '1px solid rgba(255,255,255,0.06)' }}>
                        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24, flexWrap: 'wrap', gap: 16 }}>
                          <div>
                            <div style={{ fontSize: 13, color: '#64748b', marginBottom: 4 }}>OVERALL PROFILE SCORE</div>
                            <div style={{ fontSize: 52, fontWeight: 900, color: scoreColor(profileResult.overallScore), letterSpacing: -2 }}>{profileResult.overallScore}<span style={{ fontSize: 20, color: '#475569' }}>/100</span></div>
                          </div>
                          <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap' }}>
                            {[
                              { label: 'Headline', score: profileResult.headlineScore },
                              { label: 'About', score: profileResult.aboutScore },
                              { label: 'Experience', score: profileResult.experienceScore },
                              { label: 'Skills', score: profileResult.skillsScore },
                            ].map(s => (
                                <div key={s.label} style={{ textAlign: 'center', background: '#141d2e', borderRadius: 10, padding: '12px 16px' }}>
                                  <div style={{ fontSize: 22, fontWeight: 800, color: scoreColor(s.score) }}>{s.score}</div>
                                  <div style={{ fontSize: 11, color: '#64748b', marginTop: 2 }}>{s.label}</div>
                                </div>
                            ))}
                          </div>
                        </div>
                        <p style={{ color: '#94a3b8', fontSize: 14, lineHeight: 1.7, margin: 0 }}>{profileResult.summary}</p>
                      </div>

                      {/* OPTIMIZED HEADLINE */}
                      <Section title="✦ OPTIMIZED HEADLINE" color="#0064ff">
                        <div style={{ background: '#141d2e', borderRadius: 10, padding: 16, fontSize: 15, lineHeight: 1.6, color: '#e8edf5', marginBottom: 12 }}>{profileResult.optimizedHeadline}</div>
                        <CopyBtn text={profileResult.optimizedHeadline} />
                      </Section>

                      {/* OPTIMIZED ABOUT */}
                      <Section title="✦ OPTIMIZED ABOUT SECTION" color="#0064ff">
                        <textarea readOnly value={profileResult.optimizedAbout} rows={8} style={{ width: '100%', background: '#141d2e', border: '1px solid rgba(255,255,255,0.06)', borderRadius: 10, padding: 16, color: '#e8edf5', fontSize: 14, lineHeight: 1.7, resize: 'vertical', boxSizing: 'border-box' }} />
                        <div style={{ marginTop: 10 }}><CopyBtn text={profileResult.optimizedAbout} /></div>
                      </Section>

                      {/* EXPERIENCE */}
                      {profileResult.optimizedExperience?.length > 0 && (
                          <Section title="✦ OPTIMIZED EXPERIENCE BULLETS" color="#0064ff">
                            {profileResult.optimizedExperience.map((exp, i) => (
                                <div key={i} style={{ background: '#141d2e', borderRadius: 10, padding: 16, marginBottom: 10, fontSize: 14, lineHeight: 1.6, color: '#cbd5e1' }}>
                                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12 }}>
                                    <span>{exp}</span>
                                    <button onClick={() => copy(exp)} style={{ flexShrink: 0, padding: '4px 10px', borderRadius: 6, background: 'rgba(0,100,255,0.15)', border: '1px solid rgba(0,100,255,0.3)', color: '#60a5fa', fontSize: 11, cursor: 'pointer' }}>Copy</button>
                                  </div>
                                </div>
                            ))}
                          </Section>
                      )}

                      {/* SKILLS */}
                      <Section title="✦ RECOMMENDED SKILLS" color="#00e5a0">
                        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 12 }}>
                          {profileResult.optimizedSkills?.map(s => (
                              <span key={s} style={{ padding: '6px 12px', borderRadius: 100, background: 'rgba(0,229,160,0.1)', border: '1px solid rgba(0,229,160,0.25)', color: '#00e5a0', fontSize: 13 }}>{s}</span>
                          ))}
                        </div>
                        <CopyBtn text={profileResult.optimizedSkills?.join(', ')} label="Copy All Skills" />
                      </Section>

                      {/* KEYWORDS */}
                      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
                        <Section title="⊕ KEYWORDS TO ADD" color="#00e5a0">
                          {profileResult.keywordsToAdd?.map(k => (
                              <div key={k} style={{ padding: '6px 0', borderBottom: '1px solid rgba(255,255,255,0.04)', fontSize: 13, color: '#94a3b8' }}>+ {k}</div>
                          ))}
                        </Section>
                        <Section title="⊖ KEYWORDS TO REMOVE" color="#ef4444">
                          {profileResult.keywordsToRemove?.map(k => (
                              <div key={k} style={{ padding: '6px 0', borderBottom: '1px solid rgba(255,255,255,0.04)', fontSize: 13, color: '#94a3b8' }}>− {k}</div>
                          ))}
                        </Section>
                      </div>

                      {/* PROFILE CHECKS */}
                      <Section title="◈ PROFILE CHECKS" color="#f59e0b">
                        {profileResult.profileChecks?.map((c, i) => (
                            <div key={i} style={{ padding: '14px 16px', borderRadius: 10, background: '#141d2e', marginBottom: 10, borderLeft: `3px solid ${statusColor(c.status)}` }}>
                              <div style={{ display: 'flex', gap: 10, alignItems: 'center', marginBottom: 6 }}>
                                <span style={{ fontSize: 11, fontWeight: 700, padding: '2px 8px', borderRadius: 4, background: `${statusColor(c.status)}20`, color: statusColor(c.status) }}>{c.status.toUpperCase()}</span>
                                <span style={{ fontWeight: 600, fontSize: 14 }}>{c.section}</span>
                              </div>
                              <div style={{ fontSize: 13, color: '#64748b', marginBottom: 6 }}>{c.issue}</div>
                              <div style={{ fontSize: 13, color: '#00e5a0' }}>Fix: {c.fix}</div>
                            </div>
                        ))}
                      </Section>

                      {/* VISIBILITY TIPS */}
                      <Section title="◎ VISIBILITY & CONNECTION TIPS" color="#60a5fa">
                        {profileResult.visibilityTips?.map((t, i) => (
                            <div key={i} style={{ padding: '10px 0', borderBottom: '1px solid rgba(255,255,255,0.04)', fontSize: 14, color: '#94a3b8', display: 'flex', gap: 10 }}>
                              <span style={{ color: '#0064ff', flexShrink: 0 }}>→</span>{t}
                            </div>
                        ))}
                      </Section>

                      {/* NEXT ACTIONS */}
                      <Section title="⚡ NEXT ACTIONS" color="#f59e0b">
                        {[
                          { label: 'TODAY', items: profileResult.nextActions?.today, color: '#ef4444' },
                          { label: 'THIS WEEK', items: profileResult.nextActions?.thisWeek, color: '#f59e0b' },
                          { label: 'THIS MONTH', items: profileResult.nextActions?.thisMonth, color: '#00e5a0' },
                        ].map(g => (
                            <div key={g.label} style={{ marginBottom: 16 }}>
                              <div style={{ fontSize: 11, fontWeight: 700, color: g.color, letterSpacing: 1, marginBottom: 8 }}>{g.label}</div>
                              {g.items?.map((a, i) => (
                                  <div key={i} style={{ padding: '8px 12px', borderRadius: 8, background: '#141d2e', marginBottom: 6, fontSize: 13, color: '#94a3b8', display: 'flex', gap: 10 }}>
                                    <span style={{ color: g.color }}>•</span>{a}
                                  </div>
                              ))}
                            </div>
                        ))}
                      </Section>

                      {/* ACTIONS */}
                      <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap' }}>
                        <button onClick={downloadPDF} style={{ padding: '14px 24px', borderRadius: 12, background: 'linear-gradient(135deg, #0064ff, #0040cc)', border: 'none', color: 'white', fontSize: 14, fontWeight: 700, cursor: 'pointer' }}>
                          ↓ Download Full Report
                        </button>
                        <button onClick={() => { setProfileResult(null); setHeadline(''); setAbout(''); setExperience(''); setSkills(''); setEducation(''); }} style={{ padding: '14px 24px', borderRadius: 12, background: 'transparent', border: '1px solid rgba(255,255,255,0.1)', color: '#94a3b8', fontSize: 14, cursor: 'pointer' }}>
                          ↺ Optimize Again
                        </button>
                        <button onClick={() => setTool('posts')} style={{ padding: '14px 24px', borderRadius: 12, background: 'rgba(0,229,160,0.1)', border: '1px solid rgba(0,229,160,0.25)', color: '#00e5a0', fontSize: 14, fontWeight: 600, cursor: 'pointer' }}>
                          Generate Posts →
                        </button>
                      </div>
                    </div>
                )}
              </div>
          )}

          {/* POST GENERATOR */}
          {tool === 'posts' && (
              <div style={{ maxWidth: 800, margin: '0 auto', padding: '48px 24px' }}>
                <div style={{ marginBottom: 40 }}>
                  <h2 style={{ fontSize: 32, fontWeight: 800, letterSpacing: -1, margin: '0 0 8px' }}>Post Generator</h2>
                  <p style={{ color: '#64748b', fontSize: 15 }}>Enter your topic and background. Get 5 viral LinkedIn posts in different formats — ready to copy and post.</p>
                </div>

                {!postResult ? (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                      <div>
                        <label style={{ display: 'block', fontSize: 11, fontWeight: 700, color: '#64748b', letterSpacing: 1, marginBottom: 8 }}>WHAT DO YOU WANT TO POST ABOUT? *</label>
                        <input value={postTopic} onChange={e => setPostTopic(e.target.value)} placeholder="e.g. I just landed my first freelance client after 3 months of trying..." style={{ width: '100%', padding: '14px 16px', borderRadius: 10, background: '#0f1623', border: '1px solid rgba(255,255,255,0.08)', color: '#e8edf5', fontSize: 14, boxSizing: 'border-box' }} />
                        <div style={{ fontSize: 11, color: '#475569', marginTop: 4 }}>Be specific — the more detail, the better the posts</div>
                      </div>

                      <div>
                        <label style={{ display: 'block', fontSize: 11, fontWeight: 700, color: '#64748b', letterSpacing: 1, marginBottom: 8 }}>YOUR BACKGROUND / SKILLS</label>
                        <input value={postBackground} onChange={e => setPostBackground(e.target.value)} placeholder="e.g. Self-taught developer, React/Next.js, 2 years experience, freelancer" style={{ width: '100%', padding: '14px 16px', borderRadius: 10, background: '#0f1623', border: '1px solid rgba(255,255,255,0.08)', color: '#e8edf5', fontSize: 14, boxSizing: 'border-box' }} />
                      </div>

                      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
                        <div>
                          <label style={{ display: 'block', fontSize: 11, fontWeight: 700, color: '#64748b', letterSpacing: 1, marginBottom: 8 }}>YOUR INDUSTRY</label>
                          <input value={industry} onChange={e => setIndustry(e.target.value)} placeholder="e.g. Web Development, Design, Marketing..." style={{ width: '100%', padding: '14px 16px', borderRadius: 10, background: '#0f1623', border: '1px solid rgba(255,255,255,0.08)', color: '#e8edf5', fontSize: 14, boxSizing: 'border-box' }} />
                        </div>
                        <div>
                          <label style={{ display: 'block', fontSize: 11, fontWeight: 700, color: '#64748b', letterSpacing: 1, marginBottom: 8 }}>YOUR GOAL WITH THIS POST</label>
                          <select value={postGoal} onChange={e => setPostGoal(e.target.value)} style={{ width: '100%', padding: '14px 16px', borderRadius: 10, background: '#0f1623', border: '1px solid rgba(255,255,255,0.08)', color: '#e8edf5', fontSize: 14 }}>
                            <option value="get clients">Attract freelance clients</option>
                            <option value="get job">Get job opportunities</option>
                            <option value="build brand">Build personal brand</option>
                            <option value="grow network">Grow connections</option>
                            <option value="show expertise">Show expertise</option>
                          </select>
                        </div>
                      </div>

                      {error && <div style={{ padding: '12px 16px', borderRadius: 10, background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.3)', color: '#ef4444', fontSize: 14 }}>{error}</div>}

                      <button onClick={runPostGenerator} disabled={loading} style={{ padding: '16px 32px', borderRadius: 12, background: loading ? '#1e293b' : 'linear-gradient(135deg, #0064ff, #0040cc)', border: 'none', color: 'white', fontSize: 16, fontWeight: 700, cursor: loading ? 'not-allowed' : 'pointer', marginTop: 8 }}>
                        {loading ? '⟳ Generating Viral Posts...' : 'Generate 5 Viral Posts →'}
                      </button>
                    </div>
                ) : (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                      <button onClick={() => setPostResult(null)} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 18px', borderRadius: 10, background: 'transparent', border: '1px solid rgba(255,255,255,0.1)', color: '#94a3b8', fontSize: 13, fontWeight: 600, cursor: 'pointer', width: 'fit-content' }}>← Back</button>
                      <div style={{ padding: '16px 20px', borderRadius: 12, background: 'rgba(0,100,255,0.08)', border: '1px solid rgba(0,100,255,0.2)', fontSize: 14, color: '#94a3b8', lineHeight: 1.6 }}>
                        <span style={{ color: '#60a5fa', fontWeight: 600 }}>Content Strategy: </span>{postResult.contentStrategy}
                      </div>

                      {postResult.posts?.map((p, i) => (
                          <div key={i} style={{ background: '#0f1623', borderRadius: 16, padding: 24, border: '1px solid rgba(255,255,255,0.06)' }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16, flexWrap: 'wrap', gap: 12 }}>
                              <div>
                                <div style={{ fontSize: 11, fontWeight: 700, color: '#0064ff', letterSpacing: 1, marginBottom: 4 }}>POST {i+1}</div>
                                <div style={{ fontSize: 16, fontWeight: 700 }}>{p.format}</div>
                              </div>
                              <div style={{ fontSize: 11, color: '#475569', background: '#141d2e', padding: '6px 12px', borderRadius: 8 }}>Best time: {p.bestTime}</div>
                            </div>

                            <div style={{ background: '#141d2e', borderRadius: 12, padding: 20, marginBottom: 16 }}>
                              <div style={{ fontSize: 15, fontWeight: 700, color: '#e8edf5', marginBottom: 12, lineHeight: 1.5 }}>{p.hook}</div>
                              <div style={{ fontSize: 14, color: '#94a3b8', lineHeight: 1.8, whiteSpace: 'pre-wrap' }}>{p.body}</div>
                              <div style={{ fontSize: 14, color: '#0064ff', marginTop: 12, fontWeight: 600 }}>{p.cta}</div>
                              <div style={{ marginTop: 12, display: 'flex', flexWrap: 'wrap', gap: 6 }}>
                                {p.hashtags?.map(h => (
                                    <span key={h} style={{ fontSize: 12, color: '#475569' }}>{h}</span>
                                ))}
                              </div>
                            </div>

                            <div style={{ fontSize: 12, color: '#475569', marginBottom: 14, fontStyle: 'italic' }}>💡 {p.whyItWorks}</div>

                            <CopyBtn text={`${p.hook}\n\n${p.body}\n\n${p.cta}\n\n${p.hashtags?.join(' ')}`} label="Copy Full Post" />
                          </div>
                      ))}

                      <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap' }}>
                        <button onClick={() => { setPostResult(null); setPostTopic(''); }} style={{ padding: '14px 24px', borderRadius: 12, background: 'transparent', border: '1px solid rgba(255,255,255,0.1)', color: '#94a3b8', fontSize: 14, cursor: 'pointer' }}>
                          ↺ Generate New Posts
                        </button>
                        <button onClick={() => setTool('profile')} style={{ padding: '14px 24px', borderRadius: 12, background: 'rgba(0,100,255,0.1)', border: '1px solid rgba(0,100,255,0.25)', color: '#60a5fa', fontSize: 14, fontWeight: 600, cursor: 'pointer' }}>
                          Optimize Profile →
                        </button>
                      </div>
                    </div>
                )}
              </div>
          )}
        </div>
      </div>
  );
}

function Section({ title, color, children }: { title: string; color: string; children: React.ReactNode }) {
  return (
      <div style={{ background: '#0f1623', borderRadius: 16, padding: 24, border: '1px solid rgba(255,255,255,0.06)' }}>
        <div style={{ fontSize: 11, fontWeight: 700, color, letterSpacing: 1.5, marginBottom: 16 }}>{title}</div>
        {children}
      </div>
  );
}

function CopyBtn({ text, label = '⎘ Copy' }: { text: string; label?: string }) {
  const [copied, setCopied] = useState(false);
  function handleCopy() {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }
  return (
      <button onClick={handleCopy} style={{ padding: '8px 16px', borderRadius: 8, background: copied ? 'rgba(0,229,160,0.15)' : 'rgba(0,100,255,0.15)', border: `1px solid ${copied ? 'rgba(0,229,160,0.3)' : 'rgba(0,100,255,0.3)'}`, color: copied ? '#00e5a0' : '#60a5fa', fontSize: 12, fontWeight: 600, cursor: 'pointer' }}>
        {copied ? '✓ Copied!' : label}
      </button>
  );
}